### ISSUE TITLE
I get this in 45

### ISSUE THREAD

**Issue by QuantiusBenignus** [QuantiusBenignus/blurt#2]
I get this in 45

```
GLib.Error g-spawn-exit-error-quark: Child process exited with code 1

Stack trace:
  _promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:45
  @resource:///org/gnome/shell/ui/init.js:21:20
  ### Promise created here: ###
  enable/<@file:///home/ja/.local/share/gnome-shell/extensions/blurt@quantiusbenignus.local/extension.js:36:44
  @resource:///org/gnome/shell/ui/init.js:21:20
```

_Originally posted by @jalberto in https://github.com/QuantiusBenignus/blurt/issues/1#issuecomment-1935979863_

**Comment by QuantiusBenignus** [comment]
Hi @jalberto . I have opened this as a new issue and am transferring my comment from #1.
The only way I could reproduce this error, was as expected when I made the wsi script return a code 1 on purpose by hiding one of its dependencies.
Getting an error code from the script can happen for many reasons as I make it do so when failing to find its dependencies.
It (wsi) should be run standalone first to check that the environment is configured well.
So, it is very puzzling that you can run it standalone with no complaints (as you confirm in #1) and yet get the error. 
A few questions:

    Does the script, when run from CLI, get the clipboard loaded with your transcribed text. (i.e. it reaches EOF successfully).
    If not, is "transcribe" in your path? is it finding the model files correctly? Does whisper.cpp transcribe?
    What is your (cli) shell environment? bash or zsh or something else. Have you set up any special mode of error handling?
  (Please, note that a few lines in the code need to be (un)commented if using bash. I should probably add an if condition in wsi, based on the shell).
  Any chance that the $PATH for your cli and your Gnome shell differ? Permission differences?

If you answer Yes to 1 (where CLI is a terminal window in GNOME). Then for now, I have no idea what it could be because wsi clearly exits gracefully and Gio should return success. 

Since it seems that GJS successfully constructs the path to wsi, try replacing all relative paths with absolute ones in wsi.

Please, let me know, because it seems for now that this is isolated to your environment.

Thanks!

**Comment by jalberto** [comment]
Thanks for taking your time for me :)

I think I found the issue, and it related to permissions, as I am running whisper in podman.

I will work on it when I have some time and let you know
